### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by NorDroN** [jonathantneal/node-smartthinq#1]
Hi!
Could you tell me if you succeeded in integrated with your LG-device on NodeJS?

**Comment by jonathantneal** [comment]
I created this to complete an application to start building the integration, because I am under the impression that one needs an API key. Unfortunately, my application was never accepted, or denied — no one responded. Have you had better luck?

I think I found some APIs online, which required XML to interface with, but it looks like I did not commit them to this repository.

**Comment by ciryon** [comment]
@jonathantneal where did you find information about applying for an api key?

**Comment by jonathantneal** [comment]
http://thinq.developer.lge.com/en/discover/partnership/

It looks like someone else has reverse engineered the API

https://github.com/sampsyo/wideq/blob/master/wideq.py#L13-L23

**Comment by jonathantneal** [comment]
Closing for now.
